import pytest

from tests.test_3d_constitutive_sampling import (
    test_centered_straight_guide_cell_centered_raster_is_transversely_symmetric,
    test_centered_straight_guide_te_fixture_is_weakly_multimode,
    test_complex_3d_source_profiles_are_forward_pure_before_real_projection,
    test_large_guide_runtime_profiles_do_not_couple_to_first_odd_guided_mode,
    test_lateral_rectangular_guide_secondary_pair_is_suppressed_during_profile_build,
    test_mode_source_runtime_profiles_are_transversely_parity_clean_for_all_3d_axes_and_polarizations,
    test_one_step_guide_curl_hx_source_branches_remain_individually_symmetric,
    test_one_step_lateral_guide_update_has_no_staggered_longitudinal_e_support_residual,
    test_one_step_straight_guide_update_has_no_staggered_ex_support_residual,
    test_one_step_uniform_medium_keeps_small_transverse_e_asymmetry,
    test_real_projection_preserves_forward_purity_under_current_profile_basis,
    test_runtime_gauge_and_flux_normalization_do_not_change_3d_mode_purity,
    test_second_order_mode_fit_is_exact_for_single_cosine_sequence,
    test_secondary_h_pair_is_specific_to_doubly_confined_lateral_guides,
    test_source_off_downstream_distance_sweep_metrics_are_finite,
    test_source_off_downstream_mode_metrics_are_finite_and_improve_with_more_modes,
    test_tiny_centered_straight_guide_fixture_is_small_and_transversely_symmetric,
    test_tiny_straight_guide_manual_substep_update_has_no_staggered_ex_support_residual,
    test_zeroing_longitudinal_h_branch_preserves_tiny_x_guide_ex_axis0_symmetry,
    test_zeroing_longitudinal_h_branch_preserves_y_guide_ey_axis0_symmetry,
)

pytestmark = [pytest.mark.characterization, pytest.mark.simulation, pytest.mark.slow]

test_centered_straight_guide_cell_centered_raster_is_transversely_symmetric.__test__ = (
    True
)
test_centered_straight_guide_te_fixture_is_weakly_multimode.__test__ = True
test_tiny_centered_straight_guide_fixture_is_small_and_transversely_symmetric.__test__ = True
test_second_order_mode_fit_is_exact_for_single_cosine_sequence.__test__ = True
test_complex_3d_source_profiles_are_forward_pure_before_real_projection.__test__ = True
test_large_guide_runtime_profiles_do_not_couple_to_first_odd_guided_mode.__test__ = True
test_source_off_downstream_mode_metrics_are_finite_and_improve_with_more_modes.__test__ = True
test_source_off_downstream_distance_sweep_metrics_are_finite.__test__ = True
test_real_projection_preserves_forward_purity_under_current_profile_basis.__test__ = (
    True
)
test_runtime_gauge_and_flux_normalization_do_not_change_3d_mode_purity.__test__ = True
test_lateral_rectangular_guide_secondary_pair_is_suppressed_during_profile_build.__test__ = True
test_secondary_h_pair_is_specific_to_doubly_confined_lateral_guides.__test__ = True
test_mode_source_runtime_profiles_are_transversely_parity_clean_for_all_3d_axes_and_polarizations.__test__ = True
test_one_step_uniform_medium_keeps_small_transverse_e_asymmetry.__test__ = True
test_one_step_straight_guide_update_has_no_staggered_ex_support_residual.__test__ = True
test_one_step_guide_curl_hx_source_branches_remain_individually_symmetric.__test__ = (
    True
)
test_one_step_lateral_guide_update_has_no_staggered_longitudinal_e_support_residual.__test__ = True
test_tiny_straight_guide_manual_substep_update_has_no_staggered_ex_support_residual.__test__ = True
test_zeroing_longitudinal_h_branch_preserves_tiny_x_guide_ex_axis0_symmetry.__test__ = (
    True
)
test_zeroing_longitudinal_h_branch_preserves_y_guide_ey_axis0_symmetry.__test__ = True
