"""Generate beamz/material_library/data/_generated.py from normalized JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from pprint import pformat


def build(data_path: Path, out_path: Path) -> None:
    payload = json.loads(data_path.read_text())
    export = payload["export"]
    items = payload["materials"]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "# Auto-generated by scripts/build_material_library.py\n"
        "# Do not edit manually.\n\n"
        f"MATERIAL_LIBRARY_EXPORT = {pformat(export, width=100)}\n"
        f"MATERIAL_LIBRARY_ITEMS = {pformat(items, width=100)}\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data",
        type=Path,
        default=Path("beamz/material_library/data/materials.normalized.json"),
        help="Path to normalized material JSON.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("beamz/material_library/data/_generated.py"),
        help="Path to generated Python artifact.",
    )
    args = parser.parse_args()
    build(args.data, args.out)
