#!/usr/bin/env python3
"""Generate MkDocs API stubs and structured reference data for BEAMZ."""

from __future__ import annotations

import argparse
import ast
import contextlib
import difflib
import importlib
import inspect
import io
import json
import re
import shutil
import sys
import tempfile
from dataclasses import asdict, dataclass, field, replace
from enum import Enum
from pathlib import Path
from types import ModuleType
from typing import Any

import griffe

PACKAGE_NAME = "beamz"
REFERENCE_JSON = "api-reference.json"
GENERIC_INIT_DOCSTRING = inspect.getdoc(object.__init__)
GENERATED_NOTICE = "<!-- This file is generated by scripts/update_api_docs.py. Do not edit by hand. -->"


@dataclass(frozen=True)
class ApiParameter:
    name: str
    kind: str
    annotation: str | None
    default: str | None
    required: bool
    description: str | None = None


@dataclass(frozen=True)
class ApiReturn:
    annotation: str | None
    description: str | None


@dataclass(frozen=True)
class ApiDocSection:
    kind: str
    title: str | None = None
    text: str | None = None
    items: list[dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True)
class ApiSource:
    module: str | None
    file: str | None
    line: int | None


@dataclass(frozen=True)
class ApiReferenceTarget:
    module: str
    anchor: str
    name: str
    qualified_name: str


@dataclass(frozen=True)
class ApiBaseClass:
    name: str
    qualified_name: str
    module: str | None
    import_path: str | None
    external: bool
    reference: ApiReferenceTarget | None = None


@dataclass(frozen=True)
class ApiEntry:
    name: str
    qualified_name: str
    canonical_path: str | None
    anchor: str
    kind: str
    type_name: str
    signature: str | None
    import_path: str
    source: ApiSource
    value_repr: str | None
    summary: str | None
    description: str | None
    docstring: str | None
    parameters: list[ApiParameter] = field(default_factory=list)
    returns: list[ApiReturn] = field(default_factory=list)
    sections: list[ApiDocSection] = field(default_factory=list)
    bases: list[ApiBaseClass] = field(default_factory=list)
    defined_in: str | None = None
    inherited: bool = False
    members: list[ApiEntry] = field(default_factory=list)


@dataclass(frozen=True)
class ApiModuleReference:
    name: str
    title: str
    summary: str
    entries: list[ApiEntry]


@dataclass(frozen=True)
class ApiReference:
    schema_version: int
    generated_by: str
    modules: list[ApiModuleReference]


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _default_docs_dir() -> Path:
    return _repo_root() / "docs"


def _default_output_dir() -> Path:
    return _default_docs_dir() / "api" / "reference"


def _module_sort_key(module_name: str) -> tuple[int, str]:
    return (module_name.count("."), module_name)


def _defines_all(path: Path) -> bool:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return False

    for node in tree.body:
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
        else:
            continue

        if any(isinstance(target, ast.Name) and target.id == "__all__" for target in targets):
            return True
    return False


def _candidate_module_names(package_name: str = PACKAGE_NAME) -> list[str]:
    package_dir = _repo_root() / package_name.replace(".", "/")
    if not package_dir.exists():
        raise RuntimeError(f"Package directory does not exist: {package_dir}")

    names = set()
    for path in package_dir.rglob("*.py"):
        if not _defines_all(path):
            continue

        rel_path = path.relative_to(package_dir)
        if path.name == "__init__.py":
            parts = (package_name, *rel_path.parent.parts)
        else:
            parts = (package_name, *rel_path.with_suffix("").parts)

        if any(part.startswith("_") for part in parts[1:]):
            continue
        names.add(".".join(parts))

    return sorted(names, key=_module_sort_key)


def discover_public_modules(package_name: str = PACKAGE_NAME) -> tuple[str, ...]:
    """Return importable public modules that define ``__all__``."""
    module_names: list[str] = []
    for module_name in _candidate_module_names(package_name):
        module = importlib.import_module(module_name)
        exported = getattr(module, "__all__", None)
        if exported is None:
            continue
        module_names.append(module_name)
    return tuple(module_names)


def _object_kind(obj: Any) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isfunction(obj):
        return "function"
    if isinstance(obj, ModuleType):
        return "module"
    return "object"


def _signature(obj: Any) -> str | None:
    if isinstance(obj, ModuleType):
        return None
    try:
        signature = str(inspect.signature(obj))
    except (TypeError, ValueError):
        return None
    return re.sub(r"<object object at 0x[0-9a-fA-F]+>", "<object>", signature)


def _signature_from_griffe(griffe_obj: Any, name: str) -> str | None:
    signature = _optional_griffe_attr(griffe_obj, "signature")
    if not callable(signature):
        return None

    try:
        value = str(signature())
    except Exception:
        return None

    if value.startswith(f"{name}("):
        return value.removeprefix(name)
    return value if value.startswith("(") else None


def _drop_implicit_method_parameter(signature: str | None) -> str | None:
    if not signature:
        return signature
    signature = re.sub(r"^\((self|cls),\s*", "(", signature)
    signature = re.sub(r"^\((self|cls)\)", "()", signature)
    return signature


def _docstring(obj: Any) -> str | None:
    if isinstance(obj, ModuleType):
        return inspect.getdoc(obj)

    if inspect.isclass(obj):
        docstring = inspect.getdoc(obj) or inspect.getdoc(getattr(obj, "__init__", None))
        return None if docstring == GENERIC_INIT_DOCSTRING else docstring

    obj_module = getattr(obj, "__module__", "")
    if inspect.isfunction(obj):
        return inspect.getdoc(obj)
    if isinstance(obj_module, str) and obj_module.startswith(PACKAGE_NAME):
        return inspect.getdoc(obj)
    return None


def _value_repr(obj: Any) -> str | None:
    if inspect.isclass(obj) or inspect.isfunction(obj) or isinstance(obj, ModuleType):
        return None
    value = repr(obj)
    if "0x" in value or len(value) > 80:
        return None
    return value


def _source_for(obj: Any) -> ApiSource:
    try:
        file_path = inspect.getsourcefile(obj)
        lines, line = inspect.getsourcelines(obj)
    except (OSError, TypeError):
        file_path, lines, line = None, [], None

    rel_file = None
    if file_path:
        try:
            rel_file = str(Path(file_path).resolve().relative_to(_repo_root()))
        except ValueError:
            rel_file = str(Path(file_path).resolve())

    return ApiSource(
        module=getattr(obj, "__module__", None),
        file=rel_file,
        line=line if lines else None,
    )


def _class_qualified_name(cls: type) -> str:
    module = getattr(cls, "__module__", None)
    qualname = getattr(cls, "__qualname__", getattr(cls, "__name__", str(cls)))
    return f"{module}.{qualname}" if module else qualname


def _class_bases(cls: type) -> list[ApiBaseClass]:
    bases: list[ApiBaseClass] = []
    for base in getattr(cls, "__bases__", ()):
        if base is object:
            continue

        module = getattr(base, "__module__", None)
        name = getattr(base, "__name__", str(base))
        qualified_name = _class_qualified_name(base)
        bases.append(
            ApiBaseClass(
                name=name,
                qualified_name=qualified_name,
                module=module,
                import_path=f"from {module} import {name}" if module and module != "builtins" else None,
                external=not bool(module and module.startswith(PACKAGE_NAME)),
            )
        )
    return bases


def _class_entry_keys(entry: ApiEntry) -> set[str]:
    keys = {entry.qualified_name}
    if entry.canonical_path:
        keys.add(entry.canonical_path)
    if entry.source.module:
        keys.add(f"{entry.source.module}.{entry.name}")
    return keys


def _class_reference_target(module_name: str, entry: ApiEntry) -> ApiReferenceTarget:
    return ApiReferenceTarget(
        module=module_name,
        anchor=entry.anchor,
        name=entry.name,
        qualified_name=entry.canonical_path or entry.qualified_name,
    )


def _class_reference_index(reference: ApiReference) -> dict[str, list[ApiReferenceTarget]]:
    index: dict[str, list[ApiReferenceTarget]] = {}
    for module in reference.modules:
        for entry in module.entries:
            if entry.kind != "class":
                continue

            target = _class_reference_target(module.name, entry)
            for key in _class_entry_keys(entry):
                index.setdefault(key, []).append(target)
    return index


def _best_reference_target(
    candidates: list[ApiReferenceTarget],
    base: ApiBaseClass,
    current_module_name: str,
) -> ApiReferenceTarget:
    qualified_name = base.qualified_name
    module_matches = [
        target
        for target in candidates
        if qualified_name == target.qualified_name or qualified_name.startswith(f"{target.module}.")
    ]
    if module_matches:
        return sorted(
            module_matches,
            key=lambda target: (
                -len(target.module),
                target.module != current_module_name,
                target.module,
            ),
        )[0]

    same_module = [target for target in candidates if target.module == current_module_name]
    if same_module:
        return same_module[0]
    return sorted(candidates, key=lambda target: (target.module.count("."), target.module))[0]


def _resolve_base_reference(
    base: ApiBaseClass,
    module_name: str,
    index: dict[str, list[ApiReferenceTarget]],
) -> ApiBaseClass:
    candidates = index.get(base.qualified_name)
    if not candidates:
        return base
    return replace(base, reference=_best_reference_target(candidates, base, module_name))


def _resolve_entry_references(
    entry: ApiEntry,
    module_name: str,
    index: dict[str, list[ApiReferenceTarget]],
) -> ApiEntry:
    if not entry.bases:
        return entry
    return replace(
        entry,
        bases=[
            _resolve_base_reference(base, module_name, index)
            for base in entry.bases
        ],
    )


def _resolve_reference_targets(reference: ApiReference) -> ApiReference:
    index = _class_reference_index(reference)
    return replace(
        reference,
        modules=[
            replace(
                module,
                entries=[
                    _resolve_entry_references(entry, module.name, index)
                    for entry in module.entries
                ],
            )
            for module in reference.modules
        ],
    )


def _anchor(index: int, name: str) -> str:
    slug = name.lower().replace("_", "-")
    slug = re.sub(r"[^a-z0-9-]+", "", slug).strip("-") or "entry"
    return f"api-{index}-{slug}"


def _member_anchor(parent_anchor: str, index: int, name: str) -> str:
    slug = name.lower().replace("_", "-")
    slug = re.sub(r"[^a-z0-9-]+", "", slug).strip("-") or "member"
    return f"{parent_anchor}-{index}-{slug}"


def _string_value(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, Enum):
        return str(value.value)
    return str(value)


def _json_value(value: Any) -> Any:
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, dict):
        return {str(key): _json_value(val) for key, val in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_value(item) for item in value]
    return str(value)


def _section_item(item: Any) -> dict[str, Any]:
    if hasattr(item, "as_dict"):
        return _json_value(item.as_dict())
    return {"text": _string_value(item)}


def _summary_and_description(text: str | None) -> tuple[str | None, str | None]:
    if not text:
        return None, None

    cleaned = text.strip()
    if not cleaned:
        return None, None

    paragraphs = [paragraph.strip() for paragraph in cleaned.split("\n\n") if paragraph.strip()]
    summary = paragraphs[0].replace("\n", " ")
    description = "\n\n".join(paragraphs[1:]) if len(paragraphs) > 1 else None
    return summary, description


def _parse_docstring(raw: str | None) -> tuple[str | None, str | None, list[ApiDocSection]]:
    if not raw:
        return None, None, []

    with contextlib.redirect_stderr(io.StringIO()):
        sections = griffe.Docstring(raw, parser="auto").parse("auto")

    output: list[ApiDocSection] = []
    text_blocks: list[str] = []

    for section in sections:
        kind = section.kind.value
        if kind == "text":
            text = str(section.value).strip()
            if text:
                text_blocks.append(text)
                output.append(ApiDocSection(kind="text", text=text))
        elif kind in {"parameters", "other parameters", "returns", "raises", "warns", "yields"}:
            output.append(
                ApiDocSection(
                    kind=kind,
                    items=[_section_item(item) for item in section.value],
                )
            )
        elif kind == "examples":
            examples = []
            for example_kind, example_text in section.value:
                examples.append(
                    {
                        "kind": _json_value(example_kind),
                        "text": str(example_text).strip(),
                    }
                )
            output.append(ApiDocSection(kind="examples", items=examples))
        else:
            output.append(ApiDocSection(kind=kind, text=_string_value(section.value)))

    summary, description = _summary_and_description("\n\n".join(text_blocks) or raw)
    return summary, description, output


def _section_items(sections: list[ApiDocSection], kind: str) -> list[dict[str, Any]]:
    for section in sections:
        if section.kind == kind:
            return section.items
    return []


def _parameter_descriptions(sections: list[ApiDocSection]) -> dict[str, dict[str, Any]]:
    descriptions: dict[str, dict[str, Any]] = {}
    for item in _section_items(sections, "parameters"):
        name = str(item.get("name", "")).lstrip("*")
        if name:
            descriptions[name] = item
    return descriptions


def _parameters_from_griffe(griffe_obj: Any, sections: list[ApiDocSection]) -> list[ApiParameter]:
    params = _optional_griffe_attr(griffe_obj, "parameters")
    if not params:
        return []

    descriptions = _parameter_descriptions(sections)
    output: list[ApiParameter] = []

    for parameter in params:
        if parameter.name in {"self", "cls"}:
            continue

        kind = _string_value(parameter.kind) or "unknown"
        name = parameter.name
        if kind == "variadic positional":
            name = f"*{name}"
        elif kind == "variadic keyword":
            name = f"**{name}"

        description = descriptions.get(parameter.name) or descriptions.get(name.lstrip("*")) or {}
        output.append(
            ApiParameter(
                name=name,
                kind=kind,
                annotation=_string_value(getattr(parameter, "annotation", None)),
                default=_string_value(getattr(parameter, "default", None)),
                required=bool(getattr(parameter, "required", False)),
                description=description.get("description"),
            )
        )

    return output


def _optional_griffe_attr(griffe_obj: Any, name: str) -> Any:
    try:
        return getattr(griffe_obj, name, None)
    except Exception:
        return None


def _griffe_docstring(griffe_obj: Any) -> str | None:
    docstring = _optional_griffe_attr(griffe_obj, "docstring")
    if docstring is None:
        return None
    return _string_value(getattr(docstring, "value", None))


def _returns_from_sections(sections: list[ApiDocSection]) -> list[ApiReturn]:
    returns: list[ApiReturn] = []
    for item in _section_items(sections, "returns"):
        returns.append(
            ApiReturn(
                annotation=_string_value(item.get("annotation")),
                description=item.get("description"),
            )
        )
    return returns


def _static_class_member(cls: type, name: str) -> Any | None:
    try:
        return inspect.getattr_static(cls, name)
    except AttributeError:
        return None


def _runtime_class_member(static_member: Any, cls: type, name: str) -> Any | None:
    if isinstance(static_member, (classmethod, staticmethod)):
        return static_member.__func__
    if isinstance(static_member, property):
        return static_member.fget
    if static_member is not None:
        return static_member
    return getattr(cls, name, None)


def _class_member_kind(static_member: Any, runtime_member: Any, griffe_member: Any) -> str | None:
    griffe_kind = _optional_griffe_attr(griffe_member, "kind")
    griffe_kind_value = _string_value(getattr(griffe_kind, "value", griffe_kind))

    if isinstance(static_member, classmethod):
        return "classmethod"
    if isinstance(static_member, staticmethod):
        return "staticmethod"
    if griffe_kind_value == "function" or inspect.isfunction(runtime_member) or inspect.ismethod(runtime_member):
        return "method"
    return None


def _class_member_names(cls: type, griffe_obj: Any) -> list[str]:
    members = _optional_griffe_attr(griffe_obj, "members") or {}
    names = list(members.keys()) if members else list(cls.__dict__.keys())
    return [name for name in names if not name.startswith("_")]


def _class_member_owner(cls: type, name: str) -> type | None:
    for owner in getattr(cls, "__mro__", ()):
        if name in getattr(owner, "__dict__", {}):
            return owner
    return None


def _class_member_entries(
    cls: type,
    module_name: str,
    class_name: str,
    parent_anchor: str,
    griffe_obj: Any,
) -> list[ApiEntry]:
    griffe_members = _optional_griffe_attr(griffe_obj, "members") or {}
    entries: list[ApiEntry] = []

    for member_index, member_name in enumerate(_class_member_names(cls, griffe_obj)):
        griffe_member = griffe_members.get(member_name)
        static_member = _static_class_member(cls, member_name)
        runtime_member = _runtime_class_member(static_member, cls, member_name)
        kind = _class_member_kind(static_member, runtime_member, griffe_member)
        if runtime_member is None or kind is None:
            continue

        raw_docstring = _docstring(runtime_member) or _griffe_docstring(griffe_member)
        summary, description, sections = _parse_docstring(raw_docstring)
        parameters = (
            _parameters_from_griffe(griffe_member, sections)
            if _optional_griffe_attr(griffe_member, "parameters")
            else []
        )
        signature = (
            _signature_from_griffe(griffe_member, member_name)
            or _drop_implicit_method_parameter(_signature(runtime_member))
        )
        owner = _class_member_owner(cls, member_name)
        defined_in = _class_qualified_name(owner) if owner else None

        entries.append(
            ApiEntry(
                name=member_name,
                qualified_name=f"{module_name}.{class_name}.{member_name}",
                canonical_path=_string_value(_optional_griffe_attr(griffe_member, "canonical_path")),
                anchor=_member_anchor(parent_anchor, len(entries), member_name),
                kind=kind,
                type_name=type(runtime_member).__name__,
                signature=signature,
                import_path=f"from {module_name} import {class_name}",
                source=_source_for(runtime_member),
                value_repr=None,
                summary=summary,
                description=description,
                docstring=raw_docstring,
                parameters=parameters,
                returns=_returns_from_sections(sections),
                sections=sections,
                defined_in=defined_in,
                inherited=owner is not None and owner is not cls,
            )
        )

    return entries


def _load_griffe_modules(module_names: tuple[str, ...]) -> dict[str, Any]:
    modules = {}
    for module_name in module_names:
        modules[module_name] = griffe.load(
            module_name,
            search_paths=[_repo_root()],
            docstring_parser="auto",
            resolve_aliases=True,
        )
    return modules


def _entry_for(
    module: ModuleType,
    module_name: str,
    name: str,
    index: int,
    griffe_module: Any,
) -> ApiEntry:
    try:
        obj = getattr(module, name)
    except AttributeError as exc:
        raise RuntimeError(f"{module.__name__}.__all__ exports missing name: {name}") from exc

    griffe_obj = griffe_module.members.get(name)
    raw_docstring = _docstring(obj)
    if raw_docstring is None and getattr(griffe_obj, "docstring", None):
        raw_docstring = griffe_obj.docstring.value

    summary, description, sections = _parse_docstring(raw_docstring)
    parameters = (
        _parameters_from_griffe(griffe_obj, sections)
        if _optional_griffe_attr(griffe_obj, "parameters")
        else []
    )

    anchor = _anchor(index, name)
    members = _class_member_entries(obj, module_name, name, anchor, griffe_obj) if inspect.isclass(obj) else []
    bases = _class_bases(obj) if inspect.isclass(obj) else []

    return ApiEntry(
        name=name,
        qualified_name=f"{module_name}.{name}",
        canonical_path=_string_value(_optional_griffe_attr(griffe_obj, "canonical_path")),
        anchor=anchor,
        kind=_object_kind(obj),
        type_name=type(obj).__name__,
        signature=_signature(obj),
        import_path=f"from {module_name} import {name}",
        source=_source_for(obj),
        value_repr=_value_repr(obj),
        summary=summary,
        description=description,
        docstring=raw_docstring,
        parameters=parameters,
        returns=_returns_from_sections(sections),
        sections=sections,
        bases=bases,
        members=members,
    )


def _public_module_reference(module_name: str, griffe_module: Any) -> ApiModuleReference:
    module = importlib.import_module(module_name)
    exported = getattr(module, "__all__", None)
    if exported is None:
        raise RuntimeError(f"{module_name} does not define __all__")

    entries = [
        _entry_for(module, module_name, name, index, griffe_module)
        for index, name in enumerate(exported)
    ]
    return ApiModuleReference(
        name=module_name,
        title=f"{module_name} API Reference",
        summary=f"Public exports from `{module_name}.__all__`.",
        entries=entries,
    )


def build_reference(module_names: tuple[str, ...] | None = None) -> ApiReference:
    module_names = discover_public_modules() if module_names is None else module_names
    griffe_modules = _load_griffe_modules(module_names)
    reference = ApiReference(
        schema_version=4,
        generated_by="scripts/update_api_docs.py",
        modules=[
            _public_module_reference(module_name, griffe_modules[module_name])
            for module_name in module_names
        ],
    )
    return _resolve_reference_targets(reference)


def _reference_dict(reference: ApiReference) -> dict[str, Any]:
    return asdict(reference)


def _render_mkdocstrings_module(module: ApiModuleReference) -> str:
    return "\n".join(
        [
            f"# {module.title}",
            "",
            GENERATED_NOTICE,
            "",
            module.summary,
            "",
            f"::: {module.name}",
            "    options:",
            "      members_order: __all__",
            "      show_root_heading: false",
            "      show_root_toc_entry: false",
            "      show_source: true",
            "",
        ]
    )


def _index_page(reference: ApiReference) -> str:
    lines = [
        "# API Reference",
        "",
        GENERATED_NOTICE,
        "",
        "These pages are generated from public modules that define `__all__`, using MkDocs and mkdocstrings for the reference pages and a structured JSON export for the website.",
        "",
    ]
    for module in reference.modules:
        lines.append(f"- [`{module.name}`]({module.name}.md)")
    return "\n".join(lines).rstrip() + "\n"


def _manifest(reference: ApiReference) -> dict[str, Any]:
    pages = [
        {
            "title": "Getting Started",
            "path": "getting-started.md",
        },
        {
            "title": "API Reference",
            "path": "api/reference/index.md",
        },
    ]
    pages.extend(
        {
            "title": module.name,
            "path": f"api/reference/{module.name}.md",
        }
        for module in reference.modules
    )
    return {
        "title": "BEAMZ Docs",
        "description": "Documentation content for BEAMZ. This directory is intended to be rendered by an external website, not deployed from this repository.",
        "version": 2,
        "pages": pages,
    }


def generate(output_dir: Path, module_names: tuple[str, ...] | None = None) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    reference = build_reference(module_names)

    json_path = output_dir / REFERENCE_JSON
    json_path.write_text(
        json.dumps(_reference_dict(reference), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    written.append(json_path)

    index_path = output_dir / "index.md"
    index_path.write_text(_index_page(reference), encoding="utf-8")
    written.append(index_path)

    for module in reference.modules:
        path = output_dir / f"{module.name}.md"
        path.write_text(_render_mkdocstrings_module(module), encoding="utf-8")
        written.append(path)

    return written


def generate_docs(docs_dir: Path, module_names: tuple[str, ...] | None = None) -> list[Path]:
    output_dir = docs_dir / "api" / "reference"
    if output_dir.exists():
        shutil.rmtree(output_dir)
    written = generate(output_dir, module_names)

    reference = build_reference(module_names)
    manifest_path = docs_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(_manifest(reference), indent=2) + "\n",
        encoding="utf-8",
    )
    written.append(manifest_path)
    return written


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _relative_generated_files(
    path: Path,
    ignored_names: set[str] | None = None,
) -> set[Path]:
    if not path.exists():
        return set()
    ignored_names = ignored_names or set()
    return {
        file.relative_to(path)
        for file in path.rglob("*")
        if file.suffix in {".md", ".json"} and file.name not in ignored_names
    }


def _diff_trees(
    actual_dir: Path,
    expected_dir: Path,
    ignored_names: set[str] | None = None,
) -> bool:
    expected_files = _relative_generated_files(expected_dir, ignored_names)
    actual_files = _relative_generated_files(actual_dir, ignored_names)
    all_files = sorted(expected_files | actual_files)

    stale = False
    for rel_path in all_files:
        expected_path = expected_dir / rel_path
        actual_path = actual_dir / rel_path
        expected = _read_text(expected_path)
        actual = _read_text(actual_path)
        if expected == actual:
            continue

        stale = True
        print(f"API docs differ: {actual_dir / rel_path}", file=sys.stderr)
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(actual_path),
            tofile=str(expected_path),
            lineterm="",
        )
        for line in list(diff)[:80]:
            print(line, file=sys.stderr)

    return stale


def check(output_dir: Path, module_names: tuple[str, ...] | None = None) -> int:
    with tempfile.TemporaryDirectory() as tmp:
        expected_dir = Path(tmp) / "reference"
        generate(expected_dir, module_names)
        stale = _diff_trees(output_dir, expected_dir)
        if stale:
            print("Generated API reference is stale. Run `make docs-api`.", file=sys.stderr)
            return 1
    return 0


def check_docs(docs_dir: Path, module_names: tuple[str, ...] | None = None) -> int:
    with tempfile.TemporaryDirectory() as tmp:
        expected_docs_dir = Path(tmp) / "docs"
        expected_docs_dir.mkdir(parents=True)
        generate_docs(expected_docs_dir, module_names)

        stale = _diff_trees(
            docs_dir / "api" / "reference",
            expected_docs_dir / "api" / "reference",
            ignored_names={REFERENCE_JSON},
        )
        actual_manifest = _read_text(docs_dir / "manifest.json")
        expected_manifest = _read_text(expected_docs_dir / "manifest.json")
        if actual_manifest != expected_manifest:
            stale = True
            print(f"API docs differ: {docs_dir / 'manifest.json'}", file=sys.stderr)
            diff = difflib.unified_diff(
                actual_manifest.splitlines(),
                expected_manifest.splitlines(),
                fromfile=str(docs_dir / "manifest.json"),
                tofile=str(expected_docs_dir / "manifest.json"),
                lineterm="",
            )
            for line in list(diff)[:80]:
                print(line, file=sys.stderr)

        if stale:
            print("Generated API docs are stale. Run `make docs-api`.", file=sys.stderr)
            return 1
    return 0


def clean_and_generate(output_dir: Path, module_names: tuple[str, ...] | None = None) -> None:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    generate(output_dir, module_names)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docs-dir",
        type=Path,
        default=_default_docs_dir(),
        help="Docs directory where manifest and API reference files are written.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Compatibility mode: only write API reference files to this directory.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated output differs from committed files.",
    )
    args = parser.parse_args(argv)

    if args.output_dir is not None:
        output_dir = args.output_dir.resolve()
        if args.check:
            return check(output_dir)
        clean_and_generate(output_dir)
        print(f"Wrote API reference to {output_dir}")
        return 0

    docs_dir = args.docs_dir.resolve()
    if args.check:
        return check_docs(docs_dir)

    generate_docs(docs_dir)
    print(f"Wrote API reference docs to {docs_dir / 'api' / 'reference'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
